runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /cron
  script: cron.app
  login: admin
- url: /webhook
  script: bot.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
