runtime: python27
api_version: 1
threadsafe: yes

cron:
- description: "Getting data from souce"
  url: /cron
  schedule: every 10 mins
  retry_parameters:
    min_backoff_seconds: 2.5
    max_doublings: 5
    job_retry_limit: 2

handlers:
- url: /cron
  script: cron.app
  login: admin
- url: /webhook
  script: bot.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
